
SELECT [yr]
      ,[demographic_warehouse].[dim].[mgra_denormalize].[jurisdiction]
      ,sum([emp_ag]) as [emp_ag]
      ,sum([emp_const_non_bldg_prod]) as [emp_const_non_bldg_prod] 
      ,sum([emp_const_non_bldg_office]) as [emp_const_non_bldg_office]
      ,sum([emp_utilities_prod]) as [emp_utilities_prod]
      ,sum([emp_utilities_office]) as [emp_utilities_office]
      ,sum([emp_const_bldg_prod]) as [emp_const_bldg_prod]
      ,sum([emp_const_bldg_office]) as [emp_const_bldg_office]
      ,sum([emp_mfg_prod]) as [emp_mfg_prod]
      ,sum([emp_mfg_office]) as [emp_mfg_office]
      ,sum([emp_whsle_whs]) as [emp_whsle_whs]
      ,sum([emp_trans]) as [emp_trans]
      ,sum([emp_retail]) as [emp_retail]
      ,sum([emp_prof_bus_svcs]) as [emp_prof_bus_svcs]
      ,sum([emp_prof_bus_svcs_bldg_maint]) as [emp_prof_bus_svcs_bldg_maint]
      ,sum([emp_pvt_ed_k12]) as [emp_pvt_ed_k12]
      ,sum([emp_pvt_ed_post_k12_oth]) as [emp_pvt_ed_post_k12_oth]
      ,sum([emp_health]) as [emp_health] 
      ,sum([emp_personal_svcs_office]) as [emp_personal_svcs_office]
      ,sum([emp_amusement]) as [emp_amusement]
      ,sum([emp_hotel]) as [emp_hotel]
      ,sum([emp_restaurant_bar]) as [emp_restaurant_bar]
      ,sum([emp_personal_svcs_retail]) as [emp_personal_svcs_retail]
      ,sum([emp_religious]) as [emp_religious]
      ,sum([emp_pvt_hh]) as [emp_pvt_hh]
      ,sum([emp_state_local_gov_ent]) as [emp_state_local_gov_ent]
      ,sum([emp_fed_non_mil]) as [emp_fed_non_mil]
      ,sum([emp_fed_mil]) as [emp_fed_mil]
      ,sum([emp_state_local_gov_blue]) as [emp_state_local_gov_blue]
      ,sum([emp_state_local_gov_white]) as [emp_state_local_gov_white]
      ,sum([emp_public_ed]) as [emp_public_ed]
      ,sum([emp_own_occ_dwell_mgmt]) as [emp_own_occ_dwell_mgmt]
      ,sum([emp_fed_gov_accts]) as [emp_fed_gov_accts]
      ,sum([emp_st_lcl_gov_accts]) as [emp_st_lcl_gov_accts]
      ,sum([emp_cap_accts]) as [emp_cap_accts]
      ,sum([emp_total]) as [emp_total]
      ,sum([enrollgradekto8]) as [enrollgradekto8]
      ,sum([enrollgrade9to12]) as [enrollgrade9to12]
      ,sum([collegeenroll]) as [collegeenroll]
      ,sum([othercollegeenroll]) as [othercollegeenroll]
      ,sum([adultschenrl]) as [adultschenrl]
      ,sum([hstallsoth]) as [hstallsoth]
      ,sum([hstallssam]) as [hstallssam]
      ,avg([hparkcost]) as [hparkcost]
      ,sum([dstallsoth]) as [dstallsoth]
      ,sum([dstallssam]) as [dstallssam]
      ,avg([dparkcost]) as [dparkcost]
      ,sum([mstallsoth]) as [mstallsoth]
      ,sum([mstallssam]) as [mstallssam]
      ,avg([mparkcost]) as [mparkcost]
      ,sum([hotelroomtotal]) as hotel_total
  FROM [isam].[xpef33].[abm_mgra13_based_input_np]
  INNER JOIN [demographic_warehouse].[dim].[mgra_denormalize]
  ON [demographic_warehouse].[dim].[mgra_denormalize].[mgra]=[isam].[xpef33].[abm_mgra13_based_input_np].[mgra]
  GROUP BY [yr]
      ,[demographic_warehouse].[dim].[mgra_denormalize].[jurisdiction]
  ORDER BY [yr]
      ,[demographic_warehouse].[dim].[mgra_denormalize].[jurisdiction]