SELECT [mgra_id]
      ,[mgra]
      ,[series]
      ,[region]
      ,[sra]
      ,[tract]
      ,[supervisorial]
      ,[college]
      ,[cpa]
      ,[jurisdiction]
      ,[zip]
      ,[secondary]
      ,[elementary]
      ,[msa]
      ,[sdcouncil]
      ,[transit]
      ,[unified]
      ,[jurisdiction_id]
      ,[cpa_id]
      ,[taz]
  FROM [demographic_warehouse].[dim].[mgra_denormalize]