
SELECT [scenario_id]
      ,[lu_2018]
      ,[parcel_id]
      ,[mgra]
      ,[cap_jurisdiction_id]
      ,[capacity_2]
      ,[mohub]
      ,[tier]
      ,[score]
      ,[subtier]
      ,[cap_scs]
      ,[site_id]
      ,[scs_site_id]
      ,[startdate]
      ,[compdate]
      ,[capacity_3]
      ,[scenario_cap]
      ,[cap_priority]
  FROM [urbansim].[urbansim].[scs_parcel]
