ID_information: 
    ID_inputs: 
        first_id: 'DS41'
        second_id: 'DS35'
        comparison: 'True'
        default_folder: './outputs/'
year_thresholds: 
    taz:  
        value_threshold: 0
        percentage_threshold: 0
    hs:
        value_threshold: 0
        percentage_threshold: 0
    hs_Single_Family:
        value_threshold: 0
        percentage_threshold: 0
    hs_Multiple_Family:
        value_threshold: 0
        percentage_threshold: 0
    hs_Mobile_Homes:
        value_threshold: 0
        percentage_threshold: 0
    Household Population (hh):
        value_threshold: 0
        percentage_threshold: 0
    hh_Single_Family:
        value_threshold: 0
        percentage_threshold: 0
    hh_Multiple_Family:
        value_threshold: 0
        percentage_threshold: 0
    hh_Mobile_Homes:
        value_threshold: 0
        percentage_threshold: 0
    gq_civ:
        value_threshold: 0
        percentage_threshold: 0
    Group Quarters - Military (gq_mil):
        value_threshold: 0
        percentage_threshold: 0
    Less than $15,000:
        value_threshold: 0
        percentage_threshold: 0
    $15,000 to $29,999:
        value_threshold: 0
        percentage_threshold: 0
    $30,000 to $44,999:
        value_threshold: 0
        percentage_threshold: 0
    $45,000 to $59,999:
        value_threshold: 0
        percentage_threshold: 0
    $60,000 to $74,999:
        value_threshold: 0
        percentage_threshold: 0
    $75,000 to $99,999:
        value_threshold: 0
        percentage_threshold: 0
    $100,000 to $124,999:
        value_threshold: 0
        percentage_threshold: 0
    $125,000 to $149,999:
        value_threshold: 0
        percentage_threshold: 0
    $150,000 to $199,999:
        value_threshold: 0
        percentage_threshold: 0
    $200,000 or more:
        value_threshold: 0
        percentage_threshold: 0
    hhs:
        value_threshold: 0
        percentage_threshold: 0
    pop:
        value_threshold: 0
        percentage_threshold: 0
    hhp:
        value_threshold: 0
        percentage_threshold: 0
    emp_Agricultural_and_Extractive:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_non_bldg_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_non_bldg_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_utilities_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_utilities_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_bldg_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_bldg_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_Manufacturing_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_Manufacturing_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_whsle_whs:
        value_threshold: 0
        percentage_threshold: 0
    emp_trans:
        value_threshold: 0
        percentage_threshold: 0
    emp_retail:
        value_threshold: 0
        percentage_threshold: 0
    emp_prof_bus_svcs:
        value_threshold: 0
        percentage_threshold: 0
    emp_prof_bus_svcs_bldg_maint:
        value_threshold: 0
        percentage_threshold: 0
    emp_pvt_ed_k12:
        value_threshold: 0
        percentage_threshold: 0
    emp_pvt_ed_post_k12_Other_Residential:
        value_threshold: 0
        percentage_threshold: 0
    emp_health:
        value_threshold: 0
        percentage_threshold: 0
    emp_personal_svcs_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_amusement:
        value_threshold: 0
        percentage_threshold: 0
    emp_hotel:
        value_threshold: 0
        percentage_threshold: 0
    emp_restaurant_bar:
        value_threshold: 0
        percentage_threshold: 0
    emp_personal_svcs_retail:
        value_threshold: 0
        percentage_threshold: 0
    emp_religious:
        value_threshold: 0
        percentage_threshold: 0
    emp_pvt_hh:
        value_threshold: 0
        percentage_threshold: 0
    emp_state_local_Government_ent:
        value_threshold: 0
        percentage_threshold: 0
    emp_fed_non_Military:
        value_threshold: 0
        percentage_threshold: 0
    emp_fed_Military:
        value_threshold: 0
        percentage_threshold: 0
    emp_state_local_Government_blue:
        value_threshold: 0
        percentage_threshold: 0
    emp_state_local_Government_white:
        value_threshold: 0
        percentage_threshold: 0
    emp_public_ed:
        value_threshold: 0
        percentage_threshold: 0
    emp_own_occ_dwell_mgmt:
        value_threshold: 0
        percentage_threshold: 0
    emp_fed_Government_accts:
        value_threshold: 0
        percentage_threshold: 0
    emp_st_lcl_Government_accts:
        value_threshold: 0
        percentage_threshold: 0
    emp_cap_accts:
        value_threshold: 0
        percentage_threshold: 0
    emp_total:
        value_threshold: 0
        percentage_threshold: 0
    enrollgradekto8:
        value_threshold: 0
        percentage_threshold: 0
    enrollgrade9to12:
        value_threshold: 0
        percentage_threshold: 0
    collegeenroll:
        value_threshold: 0
        percentage_threshold: 0
    othercollegeenroll:
        value_threshold: 0
        percentage_threshold: 0
    adultschenrl:
        value_threshold: 0
        percentage_threshold: 0
    ech_dist:
        value_threshold: 0
        percentage_threshold: 0
    hch_dist:
        value_threshold: 0
        percentage_threshold: 0
    pseudomsa:
        value_threshold: 0
        percentage_threshold: 0
    parkarea:
        value_threshold: 0
        percentage_threshold: 0
    hstallsoth:
        value_threshold: 0
        percentage_threshold: 0
    hstallssam:
        value_threshold: 0
        percentage_threshold: 0
    hparkcost:
        value_threshold: 0
        percentage_threshold: 0
    numfreehrs:
        value_threshold: 0
        percentage_threshold: 0
    dstallsoth:
        value_threshold: 0
        percentage_threshold: 0
    dstallssam:
        value_threshold: 0
        percentage_threshold: 0
    dparkcost:
        value_threshold: 0
        percentage_threshold: 0
    mstallsoth:
        value_threshold: 0
        percentage_threshold: 0
    mstallssam:
        value_threshold: 0
        percentage_threshold: 0
    mparkcost:
        value_threshold: 0
        percentage_threshold: 0
    totint:
        value_threshold: 0
        percentage_threshold: 0
    duden:
        value_threshold: 0
        percentage_threshold: 0
    empden:
        value_threshold: 0
        percentage_threshold: 0
    popden:
        value_threshold: 0
        percentage_threshold: 0
    retempden:
        value_threshold: 0
        percentage_threshold: 0
    totintbin:
        value_threshold: 0
        percentage_threshold: 0
    empdenbin:
        value_threshold: 0
        percentage_threshold: 0
    dudenbin:
        value_threshold: 0
        percentage_threshold: 0
    zip09:
        value_threshold: 0
        percentage_threshold: 0
    parkactive:
        value_threshold: 0
        percentage_threshold: 0
    openspaceparkpreserve:
        value_threshold: 0
        percentage_threshold: 0
    beachactive:
        value_threshold: 0
        percentage_threshold: 0
    budgetroom:
        value_threshold: 0
        percentage_threshold: 0
    economyroom:
        value_threshold: 0
        percentage_threshold: 0
    luxuryroom:
        value_threshold: 0
        percentage_threshold: 0
    midpriceroom:
        value_threshold: 0
        percentage_threshold: 0
    upscaleroom:
        value_threshold: 0
        percentage_threshold: 0
    hotelroomtotal:
        value_threshold: 0
        percentage_threshold: 0
    luz_id:
        value_threshold: 0
        percentage_threshold: 0
    truckregiontype:
        value_threshold: 0
        percentage_threshold: 0
    district27:
        value_threshold: 0
        percentage_threshold: 0
    milestocoast:
        value_threshold: 0
        percentage_threshold: 0
    acres:
        value_threshold: 0
        percentage_threshold: 0
    effective_acres:
        value_threshold: 0
        percentage_threshold: 0
    land_acres:
        value_threshold: 0
        percentage_threshold: 0
ds_thresholds:
    taz:  
        value_threshold: 0
        percentage_threshold: 0
    hs:
        value_threshold: 0
        percentage_threshold: 0
    hs_Single_Family:
        value_threshold: 0
        percentage_threshold: 0
    hs_Multiple_Family:
        value_threshold: 0
        percentage_threshold: 0
    hs_Mobile_Homes:
        value_threshold: 0
        percentage_threshold: 0
    Household Population (hh):
        value_threshold: 0
        percentage_threshold: 0
    hh_Single_Family:
        value_threshold: 0
        percentage_threshold: 0
    hh_Multiple_Family:
        value_threshold: 0
        percentage_threshold: 0
    hh_Mobile_Homes:
        value_threshold: 0
        percentage_threshold: 0
    gq_civ:
        value_threshold: 0
        percentage_threshold: 0
    Group Quarters - Military (gq_mil):
        value_threshold: 0
        percentage_threshold: 0
    Less than $15,000:
        value_threshold: 0
        percentage_threshold: 0
    $15,000 to $29,999:
        value_threshold: 0
        percentage_threshold: 0
    $30,000 to $44,999:
        value_threshold: 0
        percentage_threshold: 0
    $45,000 to $59,999:
        value_threshold: 0
        percentage_threshold: 0
    $60,000 to $74,999:
        value_threshold: 0
        percentage_threshold: 0
    $75,000 to $99,999:
        value_threshold: 0
        percentage_threshold: 0
    $100,000 to $124,999:
        value_threshold: 0
        percentage_threshold: 0
    $125,000 to $149,999:
        value_threshold: 0
        percentage_threshold: 0
    $150,000 to $199,999:
        value_threshold: 0
        percentage_threshold: 0
    $200,000 or more:
        value_threshold: 0
        percentage_threshold: 0
    hhs:
        value_threshold: 0
        percentage_threshold: 0
    pop:
        value_threshold: 0
        percentage_threshold: 0
    hhp:
        value_threshold: 0
        percentage_threshold: 0
    emp_Agricultural_and_Extractive:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_non_bldg_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_non_bldg_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_utilities_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_utilities_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_bldg_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_const_bldg_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_Manufacturing_prod:
        value_threshold: 0
        percentage_threshold: 0
    emp_Manufacturing_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_whsle_whs:
        value_threshold: 0
        percentage_threshold: 0
    emp_trans:
        value_threshold: 0
        percentage_threshold: 0
    emp_retail:
        value_threshold: 0
        percentage_threshold: 0
    emp_prof_bus_svcs:
        value_threshold: 0
        percentage_threshold: 0
    emp_prof_bus_svcs_bldg_maint:
        value_threshold: 0
        percentage_threshold: 0
    emp_pvt_ed_k12:
        value_threshold: 0
        percentage_threshold: 0
    emp_pvt_ed_post_k12_Other_Residential:
        value_threshold: 0
        percentage_threshold: 0
    emp_health:
        value_threshold: 0
        percentage_threshold: 0
    emp_personal_svcs_Office:
        value_threshold: 0
        percentage_threshold: 0
    emp_amusement:
        value_threshold: 0
        percentage_threshold: 0
    emp_hotel:
        value_threshold: 0
        percentage_threshold: 0
    emp_restaurant_bar:
        value_threshold: 0
        percentage_threshold: 0
    emp_personal_svcs_retail:
        value_threshold: 0
        percentage_threshold: 0
    emp_religious:
        value_threshold: 0
        percentage_threshold: 0
    emp_pvt_hh:
        value_threshold: 0
        percentage_threshold: 0
    emp_state_local_Government_ent:
        value_threshold: 0
        percentage_threshold: 0
    emp_fed_non_Military:
        value_threshold: 0
        percentage_threshold: 0
    emp_fed_Military:
        value_threshold: 0
        percentage_threshold: 0
    emp_state_local_Government_blue:
        value_threshold: 0
        percentage_threshold: 0
    emp_state_local_Government_white:
        value_threshold: 0
        percentage_threshold: 0
    emp_public_ed:
        value_threshold: 0
        percentage_threshold: 0
    emp_own_occ_dwell_mgmt:
        value_threshold: 0
        percentage_threshold: 0
    emp_fed_Government_accts:
        value_threshold: 0
        percentage_threshold: 0
    emp_st_lcl_Government_accts:
        value_threshold: 0
        percentage_threshold: 0
    emp_cap_accts:
        value_threshold: 0
        percentage_threshold: 0
    emp_total:
        value_threshold: 0
        percentage_threshold: 0
    enrollgradekto8:
        value_threshold: 0
        percentage_threshold: 0
    enrollgrade9to12:
        value_threshold: 0
        percentage_threshold: 0
    collegeenroll:
        value_threshold: 0
        percentage_threshold: 0
    othercollegeenroll:
        value_threshold: 0
        percentage_threshold: 0
    adultschenrl:
        value_threshold: 0
        percentage_threshold: 0
    ech_dist:
        value_threshold: 0
        percentage_threshold: 0
    hch_dist:
        value_threshold: 0
        percentage_threshold: 0
    pseudomsa:
        value_threshold: 0
        percentage_threshold: 0
    parkarea:
        value_threshold: 0
        percentage_threshold: 0
    hstallsoth:
        value_threshold: 0
        percentage_threshold: 0
    hstallssam:
        value_threshold: 0
        percentage_threshold: 0
    hparkcost:
        value_threshold: 0
        percentage_threshold: 0
    numfreehrs:
        value_threshold: 0
        percentage_threshold: 0
    dstallsoth:
        value_threshold: 0
        percentage_threshold: 0
    dstallssam:
        value_threshold: 0
        percentage_threshold: 0
    dparkcost:
        value_threshold: 0
        percentage_threshold: 0
    mstallsoth:
        value_threshold: 0
        percentage_threshold: 0
    mstallssam:
        value_threshold: 0
        percentage_threshold: 0
    mparkcost:
        value_threshold: 0
        percentage_threshold: 0
    totint:
        value_threshold: 0
        percentage_threshold: 0
    duden:
        value_threshold: 0
        percentage_threshold: 0
    empden:
        value_threshold: 0
        percentage_threshold: 0
    popden:
        value_threshold: 0
        percentage_threshold: 0
    retempden:
        value_threshold: 0
        percentage_threshold: 0
    totintbin:
        value_threshold: 0
        percentage_threshold: 0
    empdenbin:
        value_threshold: 0
        percentage_threshold: 0
    dudenbin:
        value_threshold: 0
        percentage_threshold: 0
    zip09:
        value_threshold: 0
        percentage_threshold: 0
    parkactive:
        value_threshold: 0
        percentage_threshold: 0
    openspaceparkpreserve:
        value_threshold: 0
        percentage_threshold: 0
    beachactive:
        value_threshold: 0
        percentage_threshold: 0
    budgetroom:
        value_threshold: 0
        percentage_threshold: 0
    economyroom:
        value_threshold: 0
        percentage_threshold: 0
    luxuryroom:
        value_threshold: 0
        percentage_threshold: 0
    midpriceroom:
        value_threshold: 0
        percentage_threshold: 0
    upscaleroom:
        value_threshold: 0
        percentage_threshold: 0
    hotelroomtotal:
        value_threshold: 0
        percentage_threshold: 0
    luz_id:
        value_threshold: 0
        percentage_threshold: 0
    truckregiontype:
        value_threshold: 0
        percentage_threshold: 0
    district27:
        value_threshold: 0
        percentage_threshold: 0
    milestocoast:
        value_threshold: 0
        percentage_threshold: 0
    acres:
        value_threshold: 0
        percentage_threshold: 0
    effective_acres:
        value_threshold: 0
        percentage_threshold: 0
    land_acres:
        value_threshold: 0
        percentage_threshold: 0