'35':
    T_Drive_files:
        DS35_2016: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2016_01.csv"
        DS35_2018: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2018_01.csv"
        DS35_2020: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2020_01.csv"
        DS35_2023: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2023_01.csv"
        DS35_2025: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2025_01.csv"
        DS35_2026: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2026_01.csv"
        DS35_2029: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2029_01.csv"
        DS35_2030: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2030_01.csv"
        DS35_2032: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2032_01.csv"
        DS35_2035: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2035_01.csv"
        DS35_2040: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2040_01.csv"
        DS35_2045: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2045_01.csv"
        DS35_2050: "T:/socioec/Current_Projects/XPEF31/abm_csv/mgra13_based_input2050_01.csv"
    Household_Files:
        DS35_households_2016: "T:/socioec/Current_Projects/XPEF31/abm_csv/households_2016_01.csv"
    Person_Files:
        DS35_persons_2016: "T:/socioec/Current_Projects/XPEF31/abm_csv/persons_2016_01.csv"
    forecast_ID: 14

DS39:
    DS38_2016: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2016_01.csv"
    DS38_2018: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2018_01.csv"
    DS38_2020: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2020_01.csv"
    DS38_2023: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2023_01.csv"
    DS38_2025: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2025_01.csv"
    DS38_2026: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2026_01.csv"
    DS38_2029: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2029_01.csv"
    DS38_2030: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2030_01.csv"
    DS38_2032: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2032_01.csv"
    DS38_2035: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2035_01.csv"
    DS38_2040: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2040_01.csv"
    DS38_2045: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2045_01.csv"
    DS38_2050: "T:/socioec/Current_Projects/XPEF34/abm_csv/mgra13_based_input2050_01.csv"
    forecast_ID: 14

DS41:
    DS41_2016: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2016_02.csv"
    DS41_2018: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2018_02.csv"
    DS41_2020: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2020_02.csv"
    DS41_2023: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2023_02.csv"
    DS41_2025: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2025_02.csv"
    DS41_2026: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2026_02.csv"
    DS41_2029: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2029_02.csv"
    DS41_2030: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2030_02.csv"
    DS41_2032: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2032_02.csv"
    DS41_2035: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2035_02.csv"
    DS41_2040: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2040_02.csv"
    DS41_2045: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2045_02.csv"
    DS41_2050: "T:/socioec/Current_Projects/XPEF35/abm_csv/New_mgra_based_input/mgra13_based_input2050_02.csv"
    forecast_ID: 14

DS38:
    DS38_2016: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2016_05_np.csv"
    DS38_2018: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2018_05_np.csv"
    DS38_2020: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2020_05_np.csv"
    DS38_2023: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2023_05_np.csv"
    DS38_2025: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2025_05_np.csv"
    DS38_2026: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2026_05_np.csv"
    DS38_2029: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2029_05_np.csv"
    DS38_2030: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2030_05_np.csv"
    DS38_2032: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2032_05_np.csv"
    DS38_2035: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2035_05_np.csv"
    DS38_2040: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2040_05_np.csv"
    DS38_2045: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2045_05_np.csv"
    DS38_2050: "T:/socioec/Current_Projects/XPEF33/abm_csv/new_parking/mgra13_based_input2050_05_np.csv"
    forecast_ID: 14



DS42:
    DS42_2016: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2016_05_np.csv"
    DS42_2018: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2018_05_np.csv"
    DS42_2020: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2020_05_np.csv"
    DS42_2023: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2023_05_np.csv"
    DS42_2025: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2025_05_np.csv"
    DS42_2026: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2026_05_np.csv"
    DS42_2029: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2029_05_np.csv"
    DS42_2030: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2030_05_np.csv"
    DS42_2032: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2032_05_np.csv"
    DS42_2035: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2035_05_np.csv"
    DS42_2040: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2040_05_np.csv"
    DS42_2045: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2045_05_np.csv"
    DS42_2050: "T:/socioec/Current_Projects/XPEF36/abm_csv/new_parking/New_mgra_based_input/mgra13_based_input2050_05_np.csv"
    forecast_ID: 14

DS99:
    DS42_2016: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2016_01_np.csv"
    DS42_2018: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2018_01_np.csv"
    DS42_2020: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2020_01_np.csv"
    DS42_2023: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2023_01_np.csv"
    DS42_2025: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2025_01_np.csv"
    DS42_2026: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2026_01_np.csv"
    DS42_2029: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2029_01_np.csv"
    DS42_2030: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2030_01_np.csv"
    DS42_2032: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2032_01_np.csv"
    DS42_2035: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2035_01_np.csv"
    DS42_2040: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2040_01_np.csv"
    DS42_2045: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2045_01_np.csv"
    DS42_2050: "T:/socioec/Current_Projects/XPEF40/abm_csv/mgra13_based_input2050_01_np.csv"
    forecast_ID: 14

dof:
    dof_data: "C:/Users/cra/San Diego Association of Governments/SANDAG QA QC - Documents/Projects/2022/2022-01 Regional Forecast DS 41-42/dof_data.xlsx"
